# See: https://docs.codecov.com/docs/codecov-yaml
# validate: curl -X POST --data-binary @codecov.yml https://codecov.io/validate

coverage:
  status:
    project:
      default:
        target: 0
    patch:
      default:
        target: 0

# excluding generated files and examples from the coverage report
ignore:
  - "**/gen"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.steps.dart"
  - "**/stub/**"
  - "**/tables/**"
