// Mocks generated by Mockito 5.4.6 from annotations
// in onepage/test/golden/golden_test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;
import 'dart:isolate' as _i8;

import 'package:backup/src/backup_controller.dart' as _i13;
import 'package:db_client/db_client.dart' as _i3;
import 'package:db_client/src/models/diary.dart' as _i12;
import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:exporter/src/csv_exporter.dart' as _i16;
import 'package:exporter/src/markdown_exporter.dart' as _i17;
import 'package:exporter/src/models/models.dart' as _i15;
import 'package:exporter/src/pdf_exporter.dart' as _i14;
import 'package:firebase_analytics/firebase_analytics.dart' as _i22;
import 'package:flutter/foundation.dart' as _i21;
import 'package:flutter/material.dart' as _i9;
import 'package:haptics/src/haptics.dart' as _i18;
import 'package:in_app_reviewer/src/in_app_reviewer.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:notification_client/src/models/models.dart' as _i24;
import 'package:notification_client/src/notification_client.dart' as _i23;
import 'package:package_info_plus/package_info_plus.dart' as _i6;
import 'package:prefs_client/prefs_client.dart' as _i10;
import 'package:tracker/src/tracker.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DbClientManager_1 extends _i1.SmartFake
    implements _i3.$DbClientManager {
  _Fake$DbClientManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DiariesTable_2 extends _i1.SmartFake implements _i3.$DiariesTable {
  _Fake$DiariesTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DiaryImagesTable_3 extends _i1.SmartFake
    implements _i3.$DiaryImagesTable {
  _Fake$DiaryImagesTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIndex_4 extends _i1.SmartFake implements _i2.Index {
  _FakeIndex_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_5 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_6 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_7 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_8 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_9 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_10 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_11 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiaryEntry_12 extends _i1.SmartFake implements _i3.DiaryEntry {
  _FakeDiaryEntry_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiaryImage_13 extends _i1.SmartFake implements _i3.DiaryImage {
  _FakeDiaryImage_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_14 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_15<T> extends _i1.SmartFake implements _i5.Future<T> {
  _FakeFuture_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_16<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_17<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_18<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake
    implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_19<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_20<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_21<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_22<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_23 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDbClient_24 extends _i1.SmartFake implements _i3.DbClient {
  _FakeDbClient_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDbConnection_25 extends _i1.SmartFake implements _i3.DbConnection {
  _FakeDbConnection_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePackageInfo_26 extends _i1.SmartFake implements _i6.PackageInfo {
  _FakePackageInfo_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_27 extends _i1.SmartFake implements _i7.File {
  _FakeFile_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSendPort_28 extends _i1.SmartFake implements _i8.SendPort {
  _FakeSendPort_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigatorObserver_29 extends _i1.SmartFake
    implements _i9.NavigatorObserver {
  _FakeNavigatorObserver_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PrefsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrefsClient extends _i1.Mock implements _i10.PrefsClient {
  MockPrefsClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get textInputHapticEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#textInputHapticEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get otherHapticEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#otherHapticEnabled),
            returnValue: false,
          )
          as bool);

  @override
  List<Map<String, dynamic>> get notificationSettings =>
      (super.noSuchMethod(
            Invocation.getter(#notificationSettings),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  bool get hasDeclinedInAppReview =>
      (super.noSuchMethod(
            Invocation.getter(#hasDeclinedInAppReview),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasShownDiaryImageNotice =>
      (super.noSuchMethod(
            Invocation.getter(#hasShownDiaryImageNotice),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<bool> setTextInputHapticEnabled({required bool? enabled}) =>
      (super.noSuchMethod(
            Invocation.method(#setTextInputHapticEnabled, [], {
              #enabled: enabled,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setOtherHapticEnabled({required bool? enabled}) =>
      (super.noSuchMethod(
            Invocation.method(#setOtherHapticEnabled, [], {#enabled: enabled}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setNotificationSettings(
    List<Map<String, dynamic>>? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationSettings, [settings]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setHasDeclinedInAppReview({required bool? value}) =>
      (super.noSuchMethod(
            Invocation.method(#setHasDeclinedInAppReview, [], {#value: value}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setLastInAppReviewShownAt({required int? timestamp}) =>
      (super.noSuchMethod(
            Invocation.method(#setLastInAppReviewShownAt, [], {
              #timestamp: timestamp,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setHasShownDiaryImageNotice({required bool? shown}) =>
      (super.noSuchMethod(
            Invocation.method(#setHasShownDiaryImageNotice, [], {
              #shown: shown,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [DbClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbClient extends _i1.Mock implements _i3.DbClient {
  MockDbClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_0(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i2.MigrationStrategy);

  @override
  _i3.$DbClientManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$DbClientManager_1(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i3.$DbClientManager);

  @override
  _i3.$DiariesTable get diaries =>
      (super.noSuchMethod(
            Invocation.getter(#diaries),
            returnValue: _Fake$DiariesTable_2(
              this,
              Invocation.getter(#diaries),
            ),
          )
          as _i3.$DiariesTable);

  @override
  _i3.$DiaryImagesTable get diaryImages =>
      (super.noSuchMethod(
            Invocation.getter(#diaryImages),
            returnValue: _Fake$DiaryImagesTable_3(
              this,
              Invocation.getter(#diaryImages),
            ),
          )
          as _i3.$DiaryImagesTable);

  @override
  _i2.Index get idxDiariesDate =>
      (super.noSuchMethod(
            Invocation.getter(#idxDiariesDate),
            returnValue: _FakeIndex_4(this, Invocation.getter(#idxDiariesDate)),
          )
          as _i2.Index);

  @override
  _i2.Index get idxDiaryImagesDiaryId =>
      (super.noSuchMethod(
            Invocation.getter(#idxDiaryImagesDiaryId),
            returnValue: _FakeIndex_4(
              this,
              Invocation.getter(#idxDiaryImagesDiaryId),
            ),
          )
          as _i2.Index);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
          )
          as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i2.DatabaseSchemaEntity>[],
          )
          as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_5(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i2.StreamQueryUpdateRules);

  @override
  _i2.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_6(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_7(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_8(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i11.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_9(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_10(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_11(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i5.Future<void> writeBackupToFile({required String? filePath}) =>
      (super.noSuchMethod(
            Invocation.method(#writeBackupToFile, [], {#filePath: filePath}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.DiaryEntry> insertDiary({
    required String? content,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertDiary, [], {
              #content: content,
              #date: date,
            }),
            returnValue: _i5.Future<_i3.DiaryEntry>.value(
              _FakeDiaryEntry_12(
                this,
                Invocation.method(#insertDiary, [], {
                  #content: content,
                  #date: date,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.DiaryEntry>);

  @override
  _i5.Future<List<_i12.Diary>> getDiaries({
    required DateTime? from,
    required DateTime? to,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaries, [], {#from: from, #to: to}),
            returnValue: _i5.Future<List<_i12.Diary>>.value(<_i12.Diary>[]),
          )
          as _i5.Future<List<_i12.Diary>>);

  @override
  _i5.Future<int> updateDiary({required int? id, required String? content}) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiary, [], {#id: id, #content: content}),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.DiaryEntry>> searchDiaries({
    required String? searchTerm,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchDiaries, [], {
              #searchTerm: searchTerm,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i5.Future<List<_i3.DiaryEntry>>.value(
              <_i3.DiaryEntry>[],
            ),
          )
          as _i5.Future<List<_i3.DiaryEntry>>);

  @override
  _i5.Future<int> countUniqueDaysWithContentInRange({
    required DateTime? from,
    required DateTime? to,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countUniqueDaysWithContentInRange, [], {
              #from: from,
              #to: to,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.DiaryImage> insertDiaryImage({
    required int? diaryId,
    required String? photoId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertDiaryImage, [], {
              #diaryId: diaryId,
              #photoId: photoId,
            }),
            returnValue: _i5.Future<_i3.DiaryImage>.value(
              _FakeDiaryImage_13(
                this,
                Invocation.method(#insertDiaryImage, [], {
                  #diaryId: diaryId,
                  #photoId: photoId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.DiaryImage>);

  @override
  _i5.Future<int> deleteDiaryImage({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDiaryImage, [], {#id: id}),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i2.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_14(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Ret> computeWithDatabase<Ret, DB extends _i2.GeneratedDatabase>({
    required _i5.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i2.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i5.Future<Ret>.value(v),
                ) ??
                _FakeFuture_15<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i5.Future<Ret>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i11.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_15<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_16<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_17<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_18<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_19<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_20<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_21<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
          )
          as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_22<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_22<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_15<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_15<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_15<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_23(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_23(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [BackupController].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupController extends _i1.Mock implements _i13.BackupController {
  MockBackupController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DbClient get dbClient =>
      (super.noSuchMethod(
            Invocation.getter(#dbClient),
            returnValue: _FakeDbClient_24(this, Invocation.getter(#dbClient)),
          )
          as _i3.DbClient);

  @override
  _i3.DbConnection get dbConnection =>
      (super.noSuchMethod(
            Invocation.getter(#dbConnection),
            returnValue: _FakeDbConnection_25(
              this,
              Invocation.getter(#dbConnection),
            ),
          )
          as _i3.DbConnection);

  @override
  _i6.PackageInfo get packageInfo =>
      (super.noSuchMethod(
            Invocation.getter(#packageInfo),
            returnValue: _FakePackageInfo_26(
              this,
              Invocation.getter(#packageInfo),
            ),
          )
          as _i6.PackageInfo);

  @override
  String get appName =>
      (super.noSuchMethod(
            Invocation.getter(#appName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#appName),
            ),
          )
          as String);

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  _i5.Future<void> createBackupFile() =>
      (super.noSuchMethod(
            Invocation.method(#createBackupFile, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> restoreBackupFile() =>
      (super.noSuchMethod(
            Invocation.method(#restoreBackupFile, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);
}

/// A class which mocks [PdfExporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfExporter extends _i1.Mock implements _i14.PdfExporter {
  MockPdfExporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.PackageInfo get packageInfo =>
      (super.noSuchMethod(
            Invocation.getter(#packageInfo),
            returnValue: _FakePackageInfo_26(
              this,
              Invocation.getter(#packageInfo),
            ),
          )
          as _i6.PackageInfo);

  @override
  _i5.Future<_i7.File> export({required List<_i15.ExportDiary>? entries}) =>
      (super.noSuchMethod(
            Invocation.method(#export, [], {#entries: entries}),
            returnValue: _i5.Future<_i7.File>.value(
              _FakeFile_27(
                this,
                Invocation.method(#export, [], {#entries: entries}),
              ),
            ),
          )
          as _i5.Future<_i7.File>);

  @override
  _i5.Future<_i7.File> exportMonth({
    required List<_i15.ExportDiary>? entries,
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportMonth, [], {
              #entries: entries,
              #year: year,
              #month: month,
            }),
            returnValue: _i5.Future<_i7.File>.value(
              _FakeFile_27(
                this,
                Invocation.method(#exportMonth, [], {
                  #entries: entries,
                  #year: year,
                  #month: month,
                }),
              ),
            ),
          )
          as _i5.Future<_i7.File>);

  @override
  _i5.Future<_i7.File> exportDateRange({
    required List<_i15.ExportDiary>? entries,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportDateRange, [], {
              #entries: entries,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<_i7.File>.value(
              _FakeFile_27(
                this,
                Invocation.method(#exportDateRange, [], {
                  #entries: entries,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i5.Future<_i7.File>);
}

/// A class which mocks [CsvExporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockCsvExporter extends _i1.Mock implements _i16.CsvExporter {
  MockCsvExporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.PackageInfo get packageInfo =>
      (super.noSuchMethod(
            Invocation.getter(#packageInfo),
            returnValue: _FakePackageInfo_26(
              this,
              Invocation.getter(#packageInfo),
            ),
          )
          as _i6.PackageInfo);

  @override
  _i5.Future<_i7.File> export({required List<_i15.ExportDiary>? entries}) =>
      (super.noSuchMethod(
            Invocation.method(#export, [], {#entries: entries}),
            returnValue: _i5.Future<_i7.File>.value(
              _FakeFile_27(
                this,
                Invocation.method(#export, [], {#entries: entries}),
              ),
            ),
          )
          as _i5.Future<_i7.File>);

  @override
  _i5.Future<_i7.File> exportMonth({
    required List<_i15.ExportDiary>? entries,
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportMonth, [], {
              #entries: entries,
              #year: year,
              #month: month,
            }),
            returnValue: _i5.Future<_i7.File>.value(
              _FakeFile_27(
                this,
                Invocation.method(#exportMonth, [], {
                  #entries: entries,
                  #year: year,
                  #month: month,
                }),
              ),
            ),
          )
          as _i5.Future<_i7.File>);

  @override
  _i5.Future<_i7.File> exportDateRange({
    required List<_i15.ExportDiary>? entries,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportDateRange, [], {
              #entries: entries,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<_i7.File>.value(
              _FakeFile_27(
                this,
                Invocation.method(#exportDateRange, [], {
                  #entries: entries,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i5.Future<_i7.File>);
}

/// A class which mocks [MarkdownExporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkdownExporter extends _i1.Mock implements _i17.MarkdownExporter {
  MockMarkdownExporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.PackageInfo get packageInfo =>
      (super.noSuchMethod(
            Invocation.getter(#packageInfo),
            returnValue: _FakePackageInfo_26(
              this,
              Invocation.getter(#packageInfo),
            ),
          )
          as _i6.PackageInfo);

  @override
  _i5.Future<_i7.File> export({required List<_i15.ExportDiary>? entries}) =>
      (super.noSuchMethod(
            Invocation.method(#export, [], {#entries: entries}),
            returnValue: _i5.Future<_i7.File>.value(
              _FakeFile_27(
                this,
                Invocation.method(#export, [], {#entries: entries}),
              ),
            ),
          )
          as _i5.Future<_i7.File>);

  @override
  _i5.Future<_i7.File> exportMonth({
    required List<_i15.ExportDiary>? entries,
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportMonth, [], {
              #entries: entries,
              #year: year,
              #month: month,
            }),
            returnValue: _i5.Future<_i7.File>.value(
              _FakeFile_27(
                this,
                Invocation.method(#exportMonth, [], {
                  #entries: entries,
                  #year: year,
                  #month: month,
                }),
              ),
            ),
          )
          as _i5.Future<_i7.File>);

  @override
  _i5.Future<_i7.File> exportDateRange({
    required List<_i15.ExportDiary>? entries,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportDateRange, [], {
              #entries: entries,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<_i7.File>.value(
              _FakeFile_27(
                this,
                Invocation.method(#exportDateRange, [], {
                  #entries: entries,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i5.Future<_i7.File>);
}

/// A class which mocks [Haptics].
///
/// See the documentation for Mockito's code generation for more information.
class MockHaptics extends _i1.Mock implements _i18.Haptics {
  MockHaptics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void textInputFeedback() => super.noSuchMethod(
    Invocation.method(#textInputFeedback, []),
    returnValueForMissingStub: null,
  );

  @override
  void buttonTapFeedback() => super.noSuchMethod(
    Invocation.method(#buttonTapFeedback, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleFeedback() => super.noSuchMethod(
    Invocation.method(#toggleFeedback, []),
    returnValueForMissingStub: null,
  );

  @override
  void navigationFeedback() => super.noSuchMethod(
    Invocation.method(#navigationFeedback, []),
    returnValueForMissingStub: null,
  );

  @override
  void successFeedback() => super.noSuchMethod(
    Invocation.method(#successFeedback, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [InAppReviewer].
///
/// See the documentation for Mockito's code generation for more information.
class MockInAppReviewer extends _i1.Mock implements _i19.InAppReviewer {
  MockInAppReviewer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> shouldShowReviewPrompt() =>
      (super.noSuchMethod(
            Invocation.method(#shouldShowReviewPrompt, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> requestReview() =>
      (super.noSuchMethod(
            Invocation.method(#requestReview, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> openStoreListing() =>
      (super.noSuchMethod(
            Invocation.method(#openStoreListing, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> checkAndShowReviewIfEligible() =>
      (super.noSuchMethod(
            Invocation.method(#checkAndShowReviewIfEligible, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markAsDeclined() =>
      (super.noSuchMethod(
            Invocation.method(#markAsDeclined, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recordReviewShown() =>
      (super.noSuchMethod(
            Invocation.method(#recordReviewShown, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [Tracker].
///
/// See the documentation for Mockito's code generation for more information.
class MockTracker extends _i1.Mock implements _i20.Tracker {
  MockTracker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> onFlutterError(
    _i21.FlutterErrorDetails? flutterErrorDetails, {
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #onFlutterError,
              [flutterErrorDetails],
              {#fatal: fatal},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool onPlatformError(Object? error, StackTrace? stack) =>
      (super.noSuchMethod(
            Invocation.method(#onPlatformError, [error, stack]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.SendPort isolateErrorListener() =>
      (super.noSuchMethod(
            Invocation.method(#isolateErrorListener, []),
            returnValue: _FakeSendPort_28(
              this,
              Invocation.method(#isolateErrorListener, []),
            ),
          )
          as _i8.SendPort);

  @override
  _i5.Future<void> recordError(
    Object? exception,
    StackTrace? stack, {
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordError,
              [exception, stack],
              {#fatal: fatal},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearUserId() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserId, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setUserProperties(Map<String, String?>? properties) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperties, [properties]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i9.NavigatorObserver navigatorObserver({
    String? Function(_i9.RouteSettings)? nameExtractor =
        _i22.defaultNameExtractor,
    bool Function(_i9.Route<dynamic>?)? routeFilter = _i22.defaultRouteFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigatorObserver, [], {
              #nameExtractor: nameExtractor,
              #routeFilter: routeFilter,
            }),
            returnValue: _FakeNavigatorObserver_29(
              this,
              Invocation.method(#navigatorObserver, [], {
                #nameExtractor: nameExtractor,
                #routeFilter: routeFilter,
              }),
            ),
          )
          as _i9.NavigatorObserver);

  @override
  List<_i9.NavigatorObserver> navigatorObservers({
    String? Function(_i9.RouteSettings)? nameExtractor =
        _i22.defaultNameExtractor,
    bool Function(_i9.Route<dynamic>?)? routeFilter = _i22.defaultRouteFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigatorObservers, [], {
              #nameExtractor: nameExtractor,
              #routeFilter: routeFilter,
            }),
            returnValue: <_i9.NavigatorObserver>[],
          )
          as List<_i9.NavigatorObserver>);

  @override
  _i5.Future<void> trackScreenView(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#trackScreenView, [screenName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logEvent(
    String? eventName, {
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logEvent,
              [eventName],
              {#parameters: parameters},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [NotificationClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationClient extends _i1.Mock
    implements _i23.NotificationClient {
  MockNotificationClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> scheduleNotifications(
    List<_i24.NotificationSetting>? settings, {
    required String? title,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #scheduleNotifications,
              [settings],
              {#title: title, #message: message},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelNotification(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
